apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
  tagSpecification_1: "env=dev"
  tagSpecification_2: "team=team-platform"
  tagSpecification_3: "product=workloads-dev"
  tagSpecification_4: "repo=https://github.com/Francescoeman/skynet-kubernetes-manifests"
  tagSpecification_5: "cost-center=global-it"
  tagSpecification_6: "company=Francescoeman"
  tagSpecification_7: "provisioner=ebs-csi-driver"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: skynet-efs-sc
provisioner: efs.csi.aws.com
parameters:
  directoryPerms: "700"
  ensureUniqueDirectory: "true"
  fileSystemId: fs-002023b9351fa780d
  provisioningMode: efs-ap
  tagSpecification_1: "env=dev"
  tagSpecification_2: "team=team-platform"
  tagSpecification_3: "product=workloads-dev"
  tagSpecification_4: "repo=https://github.com/Francescoeman/skynet-kubernetes-manifests"
  tagSpecification_5: "cost-center=global-it"
  tagSpecification_6: "company=Francescoeman"
  tagSpecification_7: "provisioner=efs-csi-driver"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: onetime-efs-sc
provisioner: efs.csi.aws.com
volumeBindingMode: Immediate
parameters:
  directoryPerms: "700"
  ensureUniqueDirectory: "true"
  fileSystemId: fs-049f85462c70ac6b6
  provisioningMode: efs-ap
  tagSpecification_1: "env=dev"
  tagSpecification_2: "team=team-platform"
  tagSpecification_3: "product=workloads-dev"
  tagSpecification_4: "repo=https://github.com/Francescoeman/skynet-kubernetes-manifests"
  tagSpecification_5: "cost-center=global-it"
  tagSpecification_6: "company=Francescoeman"
  tagSpecification_7: "provisioner=efs-csi-driver"
  tagSpecification_8: "project=onetime"
