apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skynet-app
  namespace: argo
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  sources:
  - path: argocd-manifests/dev/workloads/applications
    repoURL: https://github.com/Francescoeman/skynet-kubernetes-manifests.git
    targetRevision: HEAD
    directory:
      recurse: true
  - path: argocd-manifests/dev/workloads/projects
    repoURL: https://github.com/Francescoeman/skynet-kubernetes-manifests.git
    targetRevision: HEAD
    directory:
      recurse: true
