apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: argocd-repo-onetime
  namespace: argo
type: Opaque
stringData:
  name: onetime
  project: default
  type: git
  url: https://github.com/Francescoeman/onetime
