apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-repo-secrets
  namespace: argo
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-manifests/repositories
    repoURL: https://github.com/Francescoeman/skynet-kubernetes-manifests.git
    targetRevision: HEAD
    directory:
      recurse: true
