apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  - group: apps
    kind: Deployment
    name: prometheus-grafana
    namespace: prometheus
    jqPathExpressions:
    - '.spec.template.spec.containers[]?.resources'
    - '.spec.template.spec.initContainers[]?.resources'
  - group: apps
    kind: DaemonSet
    name: prometheus-prometheus-node-exporter
    namespace: prometheus
    jqPathExpressions:
    - '.spec.template.spec.containers[]?.resources'
  sources:
  - chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "72.6.3"
    helm:
      valueFiles:
      - $values/helm-values/kube-prometheus-stack/default-workloads-dev.yaml
  - path: external-secrets-helper
    repoURL: https://github.com/Francescoeman/skynet-helm-charts.git
    targetRevision: HEAD
    helm:
      releaseName: prometheus-external-secrets
      valueFiles:
      - $values/helm-values/kube-prometheus-stack/external-secrets-workloads-dev.yaml
  - path: prometheus-alertmanager-config
    repoURL: https://github.com/Francescoeman/skynet-helm-charts.git
    targetRevision: HEAD
    helm:
      releaseName: prometheus-alertmanager-config
      valueFiles:
      - $values/helm-values/kube-prometheus-stack/alertmanager-config-workloads-dev.yaml
  - repoURL: https://github.com/Francescoeman/skynet-kubernetes-manifests.git
    ref: values
