apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pv-storage-class
  namespace: argo
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-manifests/pv-storage-class/dev
    repoURL: https://github.com/Francescoeman/skynet-kubernetes-manifests.git
    targetRevision: HEAD
    directory:
      include: 'workloads.yaml'
