serviceMonitor:
  enabled: true
  namespace: prometheus
  telemetryPath: "/metrics"
  interval: 30s
  honorLabels: true
  additionalLabels:
    release: prometheus

ingress:
  enabled: true
  className: alb
  path: /
  pathType: Prefix
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
  - pushgateway.workloads-euc1.dev.skynet.cloud

additionalLabels:
  team: "team-platform"
  env: dev

podLabels:
  team: "team-platform"
  env: dev
