apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twingate-operator
  namespace: argocd
spec:
  project: skynet-project
  source:
    repoURL: https://twingate.github.io/helm-charts
    chart: twingate-operator
    targetRevision: 1.1.1 # Use the latest version from ArtifactHub
    helm:
      values: |
        # Add custom Helm values here if needed
  destination:
    server: https://kubernetes.default.svc
    namespace: twingate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true