apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: applications-project
    app.kubernetes.io/part-of: skynet-platform
    app.kubernetes.io/environment: dev
spec:
  description: Application project for user-facing applications - Development
  sourceRepos:
    - 'https://github.com/cyberdine-skynet/*'
    - 'https://charts.bitnami.com/bitnami'
    - 'https://helm.sh/stable'
  destinations:
    - namespace: 'skynet-*-dev'
      server: https://kubernetes.default.svc
    - namespace: 'app-*-dev'
      server: https://kubernetes.default.svc
  clusterResourceBlacklist:
    - group: ''
      kind: '*'
    - group: 'rbac.authorization.k8s.io'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: IngressClass
    - group: 'apiextensions.k8s.io'
      kind: '*'
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: PersistentVolumeClaim
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: ReplicaSet
    - group: 'apps'
      kind: StatefulSet
    - group: 'apps'
      kind: DaemonSet
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'networking.k8s.io'
      kind: NetworkPolicy
    - group: 'batch'
      kind: Job
    - group: 'batch'
      kind: CronJob
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler
    - group: 'policy'
      kind: PodDisruptionBudget
  roles:
    - name: app-admin
      description: Application administrators with full access to applications
      policies:
        - p, proj:applications-dev:app-admin, applications, *, applications-dev/*, allow
        - p, proj:applications-dev:app-admin, repositories, *, *, allow
      groups:
        - cyberdine-skynet:Platform
