apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: infrastructure-project
    app.kubernetes.io/part-of: skynet-platform
    app.kubernetes.io/environment: dev
spec:
  description: Infrastructure project for cluster-wide components - Development
  sourceRepos:
    - 'https://github.com/cyberdine-skynet/*'
    - 'https://charts.bitnami.com/bitnami'
    - 'https://kubernetes.github.io/ingress-nginx'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://grafana.github.io/helm-charts'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: PersistentVolume
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'networking.k8s.io'
      kind: IngressClass
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'admissionregistration.k8s.io'
      kind: ValidatingAdmissionWebhook
    - group: 'admissionregistration.k8s.io'
      kind: MutatingAdmissionWebhook
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
    - group: 'extensions'
      kind: '*'
  roles:
    - name: platform-admin
      description: Platform administrators with full access
      policies:
        - p, proj:infrastructure-dev:platform-admin, applications, *, infrastructure-dev/*, allow
        - p, proj:infrastructure-dev:platform-admin, repositories, *, *, allow
      groups:
        - cyberdine-skynet:Platform
