apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-namespaces-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: workload-namespaces
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: skynet-platform
    app.kubernetes.io/environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure-dev
  source:
    repoURL: https://github.com/cyberdine-skynet/skynet-kubernetes-manifests
    targetRevision: main
    path: app-manifests/workload-namespaces
    directory:
      recurse: true
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
