prometheus:
  service:
    type: ClusterIP
alertmanager:
  service:
    type: ClusterIP
grafana:
  enabled: true
  service:
    type: NodePort # or ClusterIP, as needed
    nodePort: 32000 # optional, only if you want NodePort
  adminUser: admin
  adminPassword: admin
