apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-system:controller
rules:
- apiGroups: [ "" ]
  resources: [ "services", "endpoints", "nodes", "secrets", "configmaps", "namespaces" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "metallb.io" ]
  resources: [ "addresspools", "bgppeers", "communities", "l2advertisements" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "admissionregistration.k8s.io" ]
  resources: [ "validatingwebhookconfigurations" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-system:controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metallb-system:controller
subjects:
- kind: ServiceAccount
  name: metallb-controller
  namespace: metallb-system
