grafana:
  enabled: true
  adminPassword: "admin"
  service:
    type: NodePort
    nodePort: 32000

loki:
  enabled: true

# Enable Fluent Bit (instead of Promtail)
fluent-bit:
  enabled: true
  config:
    outputs: |
      [OUTPUT]
          Name        loki
          Match       *
          Host        loki
          Port        3100
          LabelKeys   job,namespace,pod
  # Optionally customize parsers, filters, etc.

promtail:
  enabled: false