apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skynet-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cyberdine-skynet/skynet-kubernetes-manifests.git'
    targetRevision: main # branch or commit
    path: charts/skynet-app # <-- path to chart in repo
    helm:
      valueFiles:
      - values.yaml
      - values-talosspecific.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true