apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: platform team Project
  sourceRepos:
  - https://github.com/cyberdine-skynet/skynet-kubernetes-manifests.git
  destinations:
  - namespace: platform
    server: https://kubernetes.default.svc
  - namespace: kafka
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: 'argoproj.io'
    kind: Application
  - group: 'apps'
    kind: Deployment
  - group: ''
    kind: Pod
  - group: 'apps'
    kind: ReplicaSet
  - group: 'apps'
    kind: StatefulSet
  - group: ''
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: ''
    kind: ServiceAccount
  - group: 'external-secrets.io'
    kind: ExternalSecret
  - group: 'external-secrets.io'
    kind: SecretStore
  - group: 'monitoring.coreos.com'
    kind: ServiceMonitor
  - group: ''
    kind: PersistentVolumeClaim
  - group: kafka.strimzi.io
    kind: KafkaTopic
  - group: kafka.incubly.oss
    kind: KafkaSchema
  roles:
  - name: app-manager
    description: Privileges to platform team applications
    policies:
    - p, proj:platform:app-manager, applications, *, platform/*, allow
    - p, proj:platform:app-manager, exec, create, platform/*, allow
    groups:
    - Chromosphere-Team-Platform
    - d47e0df0-b985-49e0-a4f6-082ad5f24821
  permitOnlyProjectScopedClusters: false
