apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: skynet-platform
    app.kubernetes.io/environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure-prod
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.11.3
    helm:
      valueFiles:
        - $values/helm-values/ingress-nginx/values-prod.yaml
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.11.3
    - repoURL: https://github.com/cyberdine-skynet/skynet-kubernetes-manifests
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
