apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
  annotations:
    argocd.argoproj.io/tracking-id: traefik:/Service:traefik
spec:
  selector:
    app: traefik
  ports:
  - name: web
    port: 80
    targetPort: 80
    protocol: TCP
  - name: websecure
    port: 443
    targetPort: 443
    protocol: TCP
  - name: dashboard
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer # <-- This line is required for MetalLB
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
