apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik.fle.api64.de
spec:
  selector:
    app: traefik
  type: NodePort
  ports:
  - name: web
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080 # Puoi scegliere un valore tra 30000-32767 o lasciare che Kubernetes lo assegni
  - name: websecure
    port: 443
    targetPort: 443
    protocol: TCP
    nodePort: 30443 # Puoi scegliere un valore tra 30000-32767 o lasciare che Kubernetes lo assegni
  - name: dashboard
    port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30808
