spec:
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081 # <-- use a free port
  - name: websecure
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30444
