# Resource Quotas for Development Environment
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: skynet-dev
  labels:
    app.kubernetes.io/name: skynet-dev-quota
    app.kubernetes.io/part-of: skynet-platform
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: skynet-staging
  labels:
    app.kubernetes.io/name: skynet-staging-quota
    app.kubernetes.io/part-of: skynet-platform
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    persistentvolumeclaims: "15"
    pods: "30"
    services: "15"
    secrets: "30"
    configmaps: "30"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: skynet-prod
  labels:
    app.kubernetes.io/name: skynet-prod-quota
    app.kubernetes.io/part-of: skynet-platform
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "20"
    pods: "50"
    services: "20"
    secrets: "50"
    configmaps: "50"
