apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skynet-docs
  namespace: argocd
  labels:
    app.kubernetes.io/name: skynet-docs
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: skynet-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  source:
    repoURL: https://github.com/cyberdine-skynet/skynet-example-app
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: skynet-docs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
