apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skynet-app
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: apps
    repoURL: 'https://github.com/cyberdine-skynet/skynet-kubernetes-manifests'
    targetRevision: HEAD
  project: default
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
