ports:
  web:
    port: 80
    expose: true
    exposedPort: 80
  websecure:
    port: 443
    expose: true
    exposedPort: 443

ingressRoute:
  dashboard:
    enabled: true

service:
  type: NodePort
  spec:
    externalTrafficPolicy: Local
    ports:
    - port: 80
      nodePort: 30080
    - port: 443
      nodePort: 30443

additionalArguments:
- "--entrypoints.web.http.redirections.entryPoint.to=websecure"
- "--entrypoints.web.http.redirections.entryPoint.scheme=https"