name: CI (Reusable)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    uses: cyberdine-skynet/skynet-workflows/.github/workflows/terraform.yaml@main
    with:
      mode: plan
      aws_role_arn: "none"
      # Add other required inputs as needed
    secrets:
      CROSS_REPO_APP_ID: ${{ secrets.CROSS_REPO_APP_ID }}
      CROSS_REPO_APP_PRIVATE_KEY: ${{ secrets.CROSS_REPO_APP_PRIVATE_KEY }}
